name: Run Tests
on: push
jobs:
  execute_tests:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t express-polls .